[versions]
com-android-application = "8.1.0-alpha11"
org-jetbrains-kotlin = "1.8.10"
ksp-version = "1.8.10-1.0.9"
activity = "1.8.0-alpha01"
accompanist = "0.31.0-alpha"
yuki = "1.1.9"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version = "1.11.0-alpha02" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0-alpha02" }
kotlin-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.5.0" }
fast-json = { module = "com.alibaba.fastjson2:fastjson2-kotlin", version = "2.0.28" }
io-coil-compose = { module = "io.coil-kt:coil-compose", version = "2.3.0" }
#https://github.com/skydoves/landscapist#coil
landscapist-coil = { module = "com.github.skydoves:landscapist-coil", version = "2.1.11" }
#https://github.com/getActivity/XXPermissions
xxpermissions = { module = "com.github.getActivity:XXPermissions", version = "16.8" }
#
yukihook-api = { module = "com.highcapable.yukihookapi:api", version.ref = "yuki" }
yukihook-ksp = { module = "com.highcapable.yukihookapi:ksp-xposed", version.ref = "yuki" }
xposed-api = { module = "de.robv.android.xposed:api", version = "82" }

compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version = "2023.04.00-alpha02" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
foundation = { group = "androidx.compose.foundation", name = "foundation" }
runtime = { group = "androidx.compose.runtime", name = "runtime" }
animation = { group = "androidx.compose.animation", name = "animation" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.6.0-alpha08" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
material3 = { group = "androidx.compose.material3", name = "material3" }
com-google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
com-google-accompanist-themeadapter-material3 = { module = "com.google.accompanist:accompanist-themeadapter-material3", version.ref = "accompanist" }
com-google-android-material  = { module = "com.google.android.material:material", version = "1.9.0-beta01" }

[plugins]
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }
com-android-application = { id = "com.android.application", version.ref = "com-android-application" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "org-jetbrains-kotlin" }
