[versions]
agp = "8.0.2"
kotlin = "1.9.0-Beta"
ksp = "1.9.0-Beta-1.0.11"
activity = "1.8.0-alpha05"
accompanist = "0.31.3-beta"
yuki = "1.1.11"

[libraries]
junit = { group = "junit", name = "junit", version = "4.13.2" }
core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0-alpha05" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0-alpha02" }
kotlin-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.5.1" }
fast-json = { module = "com.alibaba.fastjson2:fastjson2-kotlin", version = "2.0.34" }
io-coil-compose = { module = "io.coil-kt:coil-compose", version = "2.4.0" }
#https://github.com/skydoves/landscapist#coil
landscapist-coil = { module = "com.github.skydoves:landscapist-coil", version = "2.2.2" }
#https://github.com/getActivity/XXPermissions
xxpermissions = { module = "com.github.getActivity:XXPermissions", version = "18.2" }
#
yukihook-api = { module = "com.highcapable.yukihookapi:api", version.ref = "yuki" }
yukihook-ksp = { module = "com.highcapable.yukihookapi:ksp-xposed", version.ref = "yuki" }
xposed-api = { module = "de.robv.android.xposed:api", version = "82" }
htmlunit = { module = "org.htmlunit:htmlunit3-android", version = "3.3.0" }
compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version = "2023.04.00-beta02" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
foundation = { group = "androidx.compose.foundation", name = "foundation" }
runtime = { group = "androidx.compose.runtime", name = "runtime" }
animation = { group = "androidx.compose.animation", name = "animation" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.6.0" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
material3 = { group = "androidx.compose.material3", name = "material3" }
com-google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
com-google-accompanist-themeadapter-material3 = { module = "com.google.accompanist:accompanist-themeadapter-material3", version.ref = "accompanist" }
com-google-android-material  = { module = "com.google.android.material:material", version = "1.10.0-alpha04" }

[plugins]
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
