[versions]
agp = "8.3.2"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.20"
yuki = "1.2.0"
compose-compiler = "1.5.11"
[libraries]
core-ktx = { module = "androidx.core:core-ktx", version = "1.13.0" }
fast-json = { module = "com.alibaba.fastjson2:fastjson2-kotlin", version = "2.0.49" }
android-material = { module = "com.google.android.material:material", version = "1.11.0" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.9.0" }
compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version = "2024.04.00-alpha02" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-material3 = { module = "androidx.compose.material3:material3", version = "1.2.1" }
compose-coil = { module = "io.coil-kt:coil-compose", version = "2.6.0" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.7.7" }
compose-lottie = { module = "com.airbnb.android:lottie-compose", version = "6.4.0" }
xposed-api = { module = "de.robv.android.xposed:api", version = "82" }
#https://github.com/HighCapable/YukiHookAPI
yukihook-api = { module = "com.highcapable.yukihookapi:api", version.ref = "yuki" }
yukihook-ksp = { module = "com.highcapable.yukihookapi:ksp-xposed", version.ref = "yuki" }
#kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
#https://github.com/LuckyPray/DexKit
dexkit = { module = "org.luckypray:dexkit", version = "2.0.1" }
xxpermissions = { module = "com.github.getActivity:XXPermissions", version = "18.63" }
[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jgit = { id = "org.lsposed.lsplugin.jgit", version = "1.1" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }