on:
  push:
    branches:
      - master

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Message [skip CI]
        env:
          COMMIT_FILTER: "[skip ci]"
        if: contains(github.event.head_commit.message, '[skip ci]')
        run: |
          echo "no 'skip ci' in commit message"
          exit 2

      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type":"types","section":"Types","hidden":false},{"type":"revert","section":"Reverts","hidden":false},{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"improvement","section":"Feature Improvements","hidden":false},{"type":"docs","section":"Docs","hidden":false},{"type":"ci","section":"CI","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'